EmptyNode:
  [KaraNode1, KaraNode2]

ExistNode:
  [ID, Name, Desc1, Desc2, LandingPageJa, LandingPageEn]

Prefix:
  land: https://landingpage.com/
  dcterms: http://purl.org/dc/terms/
  rdfs: http://www.w3.org/2000/01/rdf-schema#

Triple:
  ID:
  - [dcterms:title, Name, ObjectRule1_Literal]
  - [dcterms:description, Desc1, ObjectRule2_Literal_en]
  - [dcterms:description, Desc2, ObjectRule3_Literal_ja]
  - [rdfs:seeAlso, KaraNode1, ObjectRule4_URI]
  - [rdfs:seeAlso, KaraNode2, ObjectRule4_URI]
  KaraNode1:
  - [rdfs:seeAlso, LandingPageJa, ObjectRule4_URI]
  - [rdfs:seeAlso, LandingPageEn, ObjectRule4_URI]
  KaraNode2:
  - [rdfs:seeAlso, LandingPageJa, ObjectRule5_URI_UsePrefix]
  - [rdfs:seeAlso, LandingPageEn, ObjectRule5_URI_UsePrefix]

ObjectRule:
  ObjectRule1_Literal:
    Type: Literal
  ObjectRule2_Literal_en:
    Type: Literal
    Language: en
  ObjectRule3_Literal_ja:
    Type: Literal
    Language: ja
  ObjectRule4_URI:
    Type: URI
  ObjectRule5_URI_UsePrefix:
    Type: URI
    UsePrefix: land
