source:
  label: DrugBank
  type: Drug
  name: drugbank
  prefix: http://identifiers.org/drugbank

target:
  label: KEGG Drug
  type: Drug
  name: kegg.drug
  prefix: http://bio2rdf.org/kegg.drug\:

link:
  file: pair.tsv

  forward:
    label: KEGG Drug ID
    name: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_HOM0000071  # in homotopy relationship with

update:
  frequency: Monthly
  method: wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
