source:
  namespace: chembl.molecule
  type: Drug #スプレッドシート”IDの詳細”ではDrugに分類されているが、Molecureというサブカテゴリを用意するのが適切かもしれない
  label: ChEMBL molecure
  prefix: http://rdf.ebi.ac.uk/resource/chembl/molecule/

target:
  label: PubMed
  type: Publication
  name: PubMed
  prefix: http://identifiers.org/pubmed/

link:
  file: pair.tsv

  forward:
    namespace: purl
    label: molecule2publication
    prefix: http://purl.org/ontology/bibo/
    predicate: pmid

update:
  frequency: Monthly
  method: https://is.gd/LOoiqK