source:
  namespace: chembl.target
  type: Protein
  label: ChEMBL target
  prefix: http://identifiers.org/chembl.target/

target:
  label: Pfam
  type: Protein
  name: Pfam
  prefix: http://identifiers.org/pfam/

link:
  file: pair.tsv

  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: https://is.gd/lawckp